networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db-app:


services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: backend-FastAPI
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:13.21-alpine3.21
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-app:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - app-network